debug: false
management.endpoint.web.exposure.include: "*"

server:
  port : 8080

logging:
  level:
    ToMist.SpringBoard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

image:
  path: /Users/dongik/Documents/etc/file/

spring:
  mail:
    host: smtp.naver.com
    port: 465
    # git 올릴시 주석 처리
    username: anjdal713@naver.com
    password: #
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
    auth-code-expiration-millis: 1800000
  datasource:
#    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:board}
#    username: ${RDS_USERNAME:root}
#    password: ${RDS_PASSWORD:Beagoodlife0418!}

    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver
    h2:
      console:
        enabled: true
        path: /h2-console

  security:
    oauth2:
      client:
        registration:
          naver:
            # git 올릴 시 주석 처리
            client-id: mXYRT5hQ2NwMClYWZnJ_
            client-secret: Maj7ERz83n
            redirect-uri: http://localhost:8080/user/login
            authorization-grant-type: authorization_code
            scope: email,nickname
            client-name: Naver
          kakao:
            # git 올릴 시 주석 처리
            client-id: 4ae0b212e7d722dac59d8625ca7623a5
            scope: profile_nickname, account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    h2.console.enabled: false
    sql.init.mode: never

  data.rest:
    base-path: /actor
    detection-strategy: annotated

aws:
  s3:
    bucketName: discipline-actor
    bucket.url: https://s3.ap-northeast-2.amazonaws.com/discipline-actor
    region: ap-northeast-2
  stack:
    auto: false
  credentials:
    # git 올릴 시 주석 처리
    accessKey: AKIAVEEOCLJLOSIAOIHY
    secretKey: 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
